# Generated by Django 2.0.6 on 2019-07-20 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildings',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='images/buildings'),
        ),
    ]
